# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version: 2
final_space: true
auto_upgrade: true
console_title_template: "{{ .Folder }}"
blocks:
- type: prompt
  alignment: left
  segments:
  - type: os
    style: diamond
    leading_diamond: 
    trailing_diamond: 
    template: " {{ if .WSL }}WSL at {{ end }}{{.Icon}}  "
    properties:
      windows: 
    background: "#21c7a8"
    foreground: "#011627"
    text: ""
    duration: 0s
    namelength: 0
  - type: root
    style: powerline
    powerline_symbol: 
    template: " \uf292 "
    background: "#ef5350"
    foreground: "#ffeb95"
    text: ""
    duration: 0s
    namelength: 0
  - type: path
    style: powerline
    powerline_symbol: 
    template: "{{ path .Path .Location }}"
    properties:
      folder_icon: "\uf07c "
      folder_separator_icon: "<#011627>\ue0b1</> "
      home_icon: " \ueb06 "
      style: agnoster
    background: "#82AAFF"
    foreground: "#011627"
    text: ""
    duration: 0s
    namelength: 0
  - type: git
    style: powerline
    powerline_symbol: 
    background_templates:
    - "{{ if or (.Working.Changed) (.Staging.Changed) }}#e4cf6a{{ end }}"
    - "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#f78c6c{{ end }}"
    - "{{ if gt .Ahead 0 }}#C792EA{{ end }}"
    - "{{ if gt .Behind 0 }}#c792ea{{ end }}"
    template: " {{ url .UpstreamIcon .UpstreamURL }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} \ueb4b {{ .StashCount }}{{ end }} "
    properties:
      branch_icon: "\ue725 "
      fetch_stash_count: true
      fetch_status: true
      fetch_upstream_icon: true
      fetch_worktree_count: true
    background: "#addb67"
    foreground: "#011627"
    text: ""
    duration: 0s
    namelength: 0
  - type: executiontime
    style: diamond
    leading_diamond: "<transparent,#575656>\ue0b0</>"
    trailing_diamond: 
    template: " {{ .FormattedMs }}"
    properties:
      style: roundrock
      threshold: 0.0
    background: "#575656"
    foreground: "#d6deeb"
    text: ""
    duration: 0s
    namelength: 0
- type: prompt
  alignment: right
  segments:
  - type: shell
    style: diamond
    leading_diamond: 
    trailing_diamond: "<transparent,#d6deeb>\ue0b2</>"
    template: "\uf489  {{ .Name }} "
    background: "#d6deeb"
    foreground: "#011627"
    text: ""
    duration: 0s
    namelength: 0
  - type: sysinfo
    style: diamond
    leading_diamond: 
    trailing_diamond: "<transparent,#8f43f3>\ue0b2</>"
    template: "\ue266 {{ round .PhysicalPercentUsed .Precision }}% "
    background: "#8f43f3"
    foreground: "#ffffff"
    text: ""
    duration: 0s
    namelength: 0
  - type: angular
    style: diamond
    leading_diamond: 
    trailing_diamond: "<transparent,#ffffff>\ue0b2</>"
    template: "\ue753 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    background: "#ffffff"
    foreground: "#ce092f"
    text: ""
    duration: 0s
    namelength: 0
  - type: aws
    style: diamond
    leading_diamond: 
    trailing_diamond: "<transparent,#565656>\ue0b2</>"
    template: "\ue7ad {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} "
    background: "#565656"
    foreground: "#faa029"
    text: ""
    duration: 0s
    namelength: 0
  - type: az
    style: diamond
    leading_diamond: 
    trailing_diamond: "<transparent,#ffffff>\ue0b2</>"
    template: "\uebd8 {{ .EnvironmentName }} "
    background: "#ffffff"
    foreground: "#337bb6"
    text: ""
    duration: 0s
    namelength: 0
  - type: azfunc
    style: diamond
    leading_diamond: 
    trailing_diamond: "<transparent,#ffffff>\ue0b2</>"
    template: "\uf104<#f5bf45>\uf0e7</>\uf105 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    background: "#ffffff"
    foreground: "#5398c2"
    text: ""
    duration: 0s
    namelength: 0
  - type: cds
    style: diamond
    leading_diamond: 
    trailing_diamond: "<transparent,#5a7a94>\ue0b2</>"
    template: "\ue311  cds {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    background: "#5a7a94"
    foreground: "#100e23"
    text: ""
    duration: 0s
    namelength: 0
  - type: crystal
    style: diamond
    leading_diamond: 
    trailing_diamond: "<transparent,#000000>\ue0b2</>"
    template: "\ue370 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    background: "#ffffff"
    foreground: "#000000"
    text: ""
    duration: 0s
    namelength: 0
  - type: cf
    style: diamond
    leading_diamond: 
    trailing_diamond: "<transparent,#ffffff>\ue0b2</>"
    template: "\uf40a  cf {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    background: "#ffffff"
    foreground: "#1d5185"
    text: ""
    duration: 0s
    namelength: 0
  - type: cftarget
    style: diamond
    leading_diamond: 
    trailing_diamond: "<transparent,#ffffff>\ue0b2</>"
    template: "\uf40a {{if .Org }}{{ .Org }}{{ end }}{{ if .Space }}/{{ .Space }}{{ end }} "
    background: "#ffffff"
    foreground: "#1d5185"
    text: ""
    duration: 0s
    namelength: 0
  - type: cmake
    style: diamond
    leading_diamond: 
    trailing_diamond: "<transparent,#d2d2d2>\ue0b2</>"
    template: "<#2829b2>\ue61e</> <#be1818>\ue61d</>  cmake {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    background: "#d2d2d2"
    foreground: "#01a300"
    text: ""
    duration: 0s
    namelength: 0
  - type: dart
    style: diamond
    leading_diamond: 
    trailing_diamond: "<transparent,#e1e8e9>\ue0b2</>"
    template: "\ue798 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    background: "#e1e8e9"
    foreground: "#055b9c"
    text: ""
    duration: 0s
    namelength: 0
  - type: dotnet
    style: diamond
    leading_diamond: 
    trailing_diamond: "<transparent,#0e0e0e>\ue0b2</>"
    template: "\ue77f  {{ if .Unsupported }}\uf071{{ else }}{{ .Full }}{{ end }} "
    background: "#0e0e0e"
    foreground: "#0d6da8"
    text: ""
    duration: 0s
    namelength: 0
  - type: flutter
    style: diamond
    leading_diamond: 
    trailing_diamond: "<transparent,#06A4CE>\ue0b2</>"
    template: "\ue28e {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    background: "#06A4CE"
    foreground: "#ffffff"
    text: ""
    duration: 0s
    namelength: 0
  - type: go
    style: diamond
    leading_diamond: 
    trailing_diamond: "<transparent,#ffffff>\ue0b2</>"
    template: "\ue626 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    background: "#ffffff"
    foreground: "#06aad5"
    text: ""
    duration: 0s
    namelength: 0
  - type: haskell
    style: diamond
    leading_diamond: 
    trailing_diamond: "<transparent,#100e23>\ue0b2</>"
    template: "\ue61f {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    background: "#100e23"
    foreground: "#906cff"
    text: ""
    duration: 0s
    namelength: 0
  - type: java
    style: diamond
    leading_diamond: 
    trailing_diamond: "<transparent,#ffffff>\ue0b2</>"
    template: "\ue738 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    background: "#ffffff"
    foreground: "#ec2729"
    text: ""
    duration: 0s
    namelength: 0
  - type: julia
    style: diamond
    leading_diamond: 
    trailing_diamond: "<transparent,#945bb3>\ue0b2</>"
    template: "<#ca3c34>\ue624</> {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    background: "#945bb3"
    foreground: "#ffffff"
    text: ""
    duration: 0s
    namelength: 0
  - type: kotlin
    style: diamond
    leading_diamond: 
    trailing_diamond: "<transparent,#906cff>\ue0b2</>"
    template: "K {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    background: "#906cff"
    foreground: "#ffffff"
    text: ""
    duration: 0s
    namelength: 0
  - type: kubectl
    style: diamond
    leading_diamond: 
    trailing_diamond: "<transparent,#316ce4>\ue0b2</>"
    template: "\uf308 {{.Context}} :: {{if .Namespace}}{{.Namespace}}{{else}}default{{end}} "
    background: "#316ce4"
    foreground: "#ffffff"
    text: ""
    duration: 0s
    namelength: 0
  - type: lua
    style: diamond
    leading_diamond: 
    trailing_diamond: "<transparent,#ffffff>\ue0b2</>"
    template: "\ue620 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    background: "#ffffff"
    foreground: "#000081"
    text: ""
    duration: 0s
    namelength: 0
  - type: node
    style: diamond
    leading_diamond: 
    trailing_diamond: "<transparent,#303030>\ue0b2</>"
    template: "\ue718 {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} "
    properties:
      fetch_package_manager: true
      npm_icon: "<#cc3a3a>\ue71e</> "
      yarn_icon: "<#348cba>\ue6a7</> "
    background: "#303030"
    foreground: "#3C873A"
    text: ""
    duration: 0s
    namelength: 0
  - type: nx
    style: diamond
    leading_diamond: 
    trailing_diamond: "<transparent,#6488c0>\ue0b2</>"
    template: "Nx {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    background: "#6488c0"
    foreground: "#1e293b"
    text: ""
    duration: 0s
    namelength: 0
  - type: perl
    style: diamond
    leading_diamond: 
    trailing_diamond: "<transparent,#41436d>\ue0b2</>"
    template: "\ue769 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    background: "#41436d"
    foreground: "#ffffff"
    text: ""
    duration: 0s
    namelength: 0
  - type: php
    style: diamond
    leading_diamond: 
    trailing_diamond: "<transparent,#787CB5>\ue0b2</>"
    template: "\ue73d {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    background: "#787CB5"
    foreground: "#000000"
    text: ""
    duration: 0s
    namelength: 0
  - type: python
    style: diamond
    leading_diamond: 
    trailing_diamond: "<transparent,#306998>\ue0b2</>"
    template:   {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}
    background: "#306998"
    foreground: "#FFE873"
    text: ""
    duration: 0s
    namelength: 0
  - type: r
    style: diamond
    leading_diamond: 
    trailing_diamond: "<transparent,#b9bbbf>\ue0b2</>"
    template: "R {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    background: "#b9bbbf"
    foreground: "#1c68bd"
    text: ""
    duration: 0s
    namelength: 0
  - type: ruby
    style: diamond
    leading_diamond: 
    trailing_diamond: "<transparent,#ffffff>\ue0b2</>"
    template: "\ue791 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    background: "#ffffff"
    foreground: "#9c1006"
    text: ""
    duration: 0s
    namelength: 0
  - type: rust
    style: diamond
    leading_diamond: 
    trailing_diamond: "<transparent,#ffffff>\ue0b2</>"
    template: "\ue7a8 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    background: "#ffffff"
    foreground: "#000000"
    text: ""
    duration: 0s
    namelength: 0
  - type: swift
    style: diamond
    leading_diamond: 
    trailing_diamond: "<transparent,#fe562e>\ue0b2</>"
    template: "\ue755 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    background: "#fe562e"
    foreground: "#ffffff"
    text: ""
    duration: 0s
    namelength: 0
  - type: battery
    style: diamond
    leading_diamond: 
    trailing_diamond: 
    foreground: "#193549"
    background: "#ffeb3b"
    background_templates:
      - '{{if eq "Charging" .State.String}}#40c4ff{{end}}'
      - '{{if eq "Discharging" .State.String}}#ff5722{{end}}'
      - '{{if eq "Full" .State.String}}#4caf50{{end}}'
    template: " {{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }} "
    properties:
      discharging_icon: " "
      charging_icon: " "
      charged_icon: " "
  overflow: break
- type: prompt
  alignment: left
  segments:
  - type: status
    style: plain
    foreground_templates:
    - "{{ if gt .Code 0 }}#ef5350{{ end }}"
    template: 
    properties:
      always_enabled: true
    background: ""
    foreground: "#22da6e"
    text: ""
    duration: 0s
    namelength: 0
  newline: true
transient_prompt:
  template: "\ue285 "
  background: transparent
  foreground: "#d6deeb"
  text: ""
  duration: 0s
  namelength: 0
